# a mybinder.org-ready environment for demoing jupyterlab_night
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-night-demo
#
name: jupyterlab-night-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.12,<3.13
  - jupyterlab >=4,<5
  # labextension build dependencies
  - nodejs >=22,<24
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
